syntax = "proto3";
package Protocol;

import "Enum.proto";
import "Struct.proto";

option csharp_namespace = "Google.Protobuf.Protocol";


message C_LOGIN
{
	int32 player_index = 1;
	string nickname = 2;
}

message S_LOGIN
{
	int32 player_index = 1;
	bool success = 2;
}

message C_ENTER_GAME
{
	int32 playerIndex = 1;
	int32 roomId = 2;
}

message C_LEAVE_GAME
{
	int32 player_index = 1;
	int32 roomId = 2;
}

message S_ENTER_GAME
{
	bool success = 1;
	ObjectInfo player = 2;
}

message S_SPAWN
{
	ObjectInfo objects = 1;
}

message C_SPAWN
{
	ObjectInfo objects = 1;
}

message C_MOVE
{
	int32 room_id = 1;
	int32 object_id = 2;
	PosInfo start_pos = 3;
	PosInfo target_pos = 4;
	int32 client_time = 5;	// 클라이언트 기준 시간, 추측항법 보정용
}

message S_MOVE
{
	int32 room_id = 1;
	int32 object_id = 2;
	PosInfo server_pos_info = 3;
	int32 server_time = 4;
	bool corrected = 5;		// 클라이언트 예측위치와 차이가 있는가?
}

message S_MOVE_END
{
	int32 room_id = 1;
    int32 object_id = 2;
    PosInfo server_pos_info = 3;
    int32 server_time = 4;
    bool corrected = 5;
}

message S_MINION_MOVE
{
	int32 object_id = 1;
	PosInfo start_pos = 2;
	repeated PosInfo nav_path = 3;
	float   speed      = 4;
}

message C_SKILL
{
	SkillType skill_id = 1;
	int32 target_id = 2;
	int32 attacker_id = 3;
	int32 room_id = 4;
	int32 client_time = 5;
}

message S_SKILL
{
	int32 skill_id = 1;
	int64 target_id = 2;
	int64 attacker_id = 3;
}

message C_ENTER_LOBBY
{
	int32 player_index = 1;
}

message S_ENTER_LOBBY
{
	int32 player_id = 1;
	repeated RoomInfo room_infos = 2;
}

message S_DIE
{
	int32 room_id = 1;
	int32 target_id = 2;
}