// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqCAQoKT2JqZWN0VHlwZRIUChBPQkpF",
            "Q1RfVFlQRV9OT05FEAASGAoUT0JKRUNUX1RZUEVfQ1JFQVRVUkUQARIWChJP",
            "QkpFQ1RfVFlQRV9QTEFZRVIQAhIXChNPQkpFQ1RfVFlQRV9NT05TVEVSEAMS",
            "EwoPT0JKRUNUX1RZUEVfRU5WEAQqiQEKClBsYXllclR5cGUSFAoQUExBWUVS",
            "X1RZUEVfTk9ORRAAEhYKElBMQVlFUl9UWVBFX1BPTElDRRABEhQKEFBMQVlF",
            "Ul9UWVBFX01PTksQAhIaChZQTEFZRVJfVFlQRV9MSUdIVFNBQlJFEAMSGwoX",
            "UExBWUVSX1RZUEVfRklSRUZJR0hURVIQBCqIAQoJTW92ZVN0YXRlEhMKD01P",
            "VkVfU1RBVEVfTk9ORRAAEhMKD01PVkVfU1RBVEVfSURMRRABEhIKDk1PVkVf",
            "U1RBVEVfUlVOEAISEwoPTU9WRV9TVEFURV9KVU1QEAMSFAoQTU9WRV9TVEFU",
            "RV9TS0lMTBAEEhIKDk1PVkVfU1RBVEVfRElFEAUqXAoJU2tpbGxUeXBlEhEK",
            "DVNLSUxMX0lEX05PTkUQABITCg9TS0lMTF9JRF9BVFRBQ0sQARISCg5TS0lM",
            "TF9JRF9GSVJTVBACEhMKD1NLSUxMX0lEX1NFQ09ORBADKj4KCENhbXBUeXBl",
            "Eg4KCkNBTVBfSFVNQU4QABIPCgtDQU1QX0NZQk9SRxABEhEKDUNBTVBfTkVV",
            "VFVSQUwQAioeCglDZWxsRmxhZ3MSEQoNQ0VMTF9XQUxLQUJMRRAAKkkKCUNl",
            "bGxMaW5rcxIOCgpMSU5LX05PUlRIEAASDQoJTElOS19FQVNUEAESDgoKTElO",
            "S19TT1VUSBACEg0KCUxJTktfV0VTVBADQheqAhRHb29nbGUuUHJvdG9idWYu",
            "RW51bWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.ObjectType), typeof(global::Google.Protobuf.Enum.PlayerType), typeof(global::Google.Protobuf.Enum.MoveState), typeof(global::Google.Protobuf.Enum.SkillType), typeof(global::Google.Protobuf.Enum.CampType), typeof(global::Google.Protobuf.Enum.CellFlags), typeof(global::Google.Protobuf.Enum.CellLinks), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ObjectType {
    [pbr::OriginalName("OBJECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("OBJECT_TYPE_CREATURE")] Creature = 1,
    [pbr::OriginalName("OBJECT_TYPE_PLAYER")] Player = 2,
    [pbr::OriginalName("OBJECT_TYPE_MONSTER")] Monster = 3,
    [pbr::OriginalName("OBJECT_TYPE_ENV")] Env = 4,
  }

  public enum PlayerType {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] None = 0,
    [pbr::OriginalName("PLAYER_TYPE_POLICE")] Police = 1,
    [pbr::OriginalName("PLAYER_TYPE_MONK")] Monk = 2,
    [pbr::OriginalName("PLAYER_TYPE_LIGHTSABRE")] Lightsabre = 3,
    [pbr::OriginalName("PLAYER_TYPE_FIREFIGHTER")] Firefighter = 4,
  }

  public enum MoveState {
    [pbr::OriginalName("MOVE_STATE_NONE")] None = 0,
    [pbr::OriginalName("MOVE_STATE_IDLE")] Idle = 1,
    [pbr::OriginalName("MOVE_STATE_RUN")] Run = 2,
    [pbr::OriginalName("MOVE_STATE_JUMP")] Jump = 3,
    [pbr::OriginalName("MOVE_STATE_SKILL")] Skill = 4,
    [pbr::OriginalName("MOVE_STATE_DIE")] Die = 5,
  }

  public enum SkillType {
    [pbr::OriginalName("SKILL_ID_NONE")] SkillIdNone = 0,
    [pbr::OriginalName("SKILL_ID_ATTACK")] SkillIdAttack = 1,
    [pbr::OriginalName("SKILL_ID_FIRST")] SkillIdFirst = 2,
    [pbr::OriginalName("SKILL_ID_SECOND")] SkillIdSecond = 3,
  }

  public enum CampType {
    [pbr::OriginalName("CAMP_HUMAN")] CampHuman = 0,
    [pbr::OriginalName("CAMP_CYBORG")] CampCyborg = 1,
    [pbr::OriginalName("CAMP_NEUTURAL")] CampNeutural = 2,
  }

  public enum CellFlags {
    [pbr::OriginalName("CELL_WALKABLE")] CellWalkable = 0,
  }

  public enum CellLinks {
    [pbr::OriginalName("LINK_NORTH")] LinkNorth = 0,
    [pbr::OriginalName("LINK_EAST")] LinkEast = 1,
    [pbr::OriginalName("LINK_SOUTH")] LinkSouth = 2,
    [pbr::OriginalName("LINK_WEST")] LinkWest = 3,
  }

  #endregion

}

#endregion Designer generated code
