// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqBAQoKT2JqZWN0VHlwZRIUChBPQkpF",
            "Q1RfVFlQRV9OT05FEAASFgoST0JKRUNUX1RZUEVfUExBWUVSEAESFgoST0JK",
            "RUNUX1RZUEVfTUlOSU9OEAISFgoST0JKRUNUX1RZUEVfVFVSUkVUEAMSFQoR",
            "T0JKRUNUX1RZUEVfTkVYVVMQBCqJAQoKUGxheWVyVHlwZRIUChBQTEFZRVJf",
            "VFlQRV9OT05FEAASFgoSUExBWUVSX1RZUEVfUE9MSUNFEAESFAoQUExBWUVS",
            "X1RZUEVfTU9OSxACEhoKFlBMQVlFUl9UWVBFX0xJR0hUU0FCUkUQAxIbChdQ",
            "TEFZRVJfVFlQRV9GSVJFRklHSFRFUhAEKogBCglNb3ZlU3RhdGUSEwoPTU9W",
            "RV9TVEFURV9OT05FEAASEwoPTU9WRV9TVEFURV9JRExFEAESEgoOTU9WRV9T",
            "VEFURV9SVU4QAhITCg9NT1ZFX1NUQVRFX0pVTVAQAxIUChBNT1ZFX1NUQVRF",
            "X1NLSUxMEAQSEgoOTU9WRV9TVEFURV9ESUUQBSpyCgtNaW5pb25TdGF0ZRIP",
            "CgtNSU5JT05fSURMRRAAEhUKEU1JTklPTl9MSU5FX1RSQUNFEAESFwoTTUlO",
            "SU9OX0NIQVNFX1RBUkdFVBACEhEKDU1JTklPTl9BVFRBQ0sQAxIPCgtNSU5J",
            "T05fREVBRBAEKlwKCVNraWxsVHlwZRIRCg1TS0lMTF9JRF9OT05FEAASEwoP",
            "U0tJTExfSURfQVRUQUNLEAESEgoOU0tJTExfSURfRklSU1QQAhITCg9TS0lM",
            "TF9JRF9TRUNPTkQQAypNCghDYW1wVHlwZRINCglDQU1QX05PTkUQABIOCgpD",
            "QU1QX0hVTUFOEAESDwoLQ0FNUF9DWUJPUkcQAhIRCg1DQU1QX05FVVRVUkFM",
            "EAMqHgoJQ2VsbEZsYWdzEhEKDUNFTExfV0FMS0FCTEUQACpJCglDZWxsTGlu",
            "a3MSDgoKTElOS19OT1JUSBAAEg0KCUxJTktfRUFTVBABEg4KCkxJTktfU09V",
            "VEgQAhINCglMSU5LX1dFU1QQA0IXqgIUR29vZ2xlLlByb3RvYnVmLkVudW1i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.ObjectType), typeof(global::Google.Protobuf.Enum.PlayerType), typeof(global::Google.Protobuf.Enum.MoveState), typeof(global::Google.Protobuf.Enum.MinionState), typeof(global::Google.Protobuf.Enum.SkillType), typeof(global::Google.Protobuf.Enum.CampType), typeof(global::Google.Protobuf.Enum.CellFlags), typeof(global::Google.Protobuf.Enum.CellLinks), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ObjectType {
    [pbr::OriginalName("OBJECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("OBJECT_TYPE_PLAYER")] Player = 1,
    [pbr::OriginalName("OBJECT_TYPE_MINION")] Minion = 2,
    [pbr::OriginalName("OBJECT_TYPE_TURRET")] Turret = 3,
    [pbr::OriginalName("OBJECT_TYPE_NEXUS")] Nexus = 4,
  }

  public enum PlayerType {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] None = 0,
    [pbr::OriginalName("PLAYER_TYPE_POLICE")] Police = 1,
    [pbr::OriginalName("PLAYER_TYPE_MONK")] Monk = 2,
    [pbr::OriginalName("PLAYER_TYPE_LIGHTSABRE")] Lightsabre = 3,
    [pbr::OriginalName("PLAYER_TYPE_FIREFIGHTER")] Firefighter = 4,
  }

  public enum MoveState {
    [pbr::OriginalName("MOVE_STATE_NONE")] None = 0,
    [pbr::OriginalName("MOVE_STATE_IDLE")] Idle = 1,
    [pbr::OriginalName("MOVE_STATE_RUN")] Run = 2,
    [pbr::OriginalName("MOVE_STATE_JUMP")] Jump = 3,
    [pbr::OriginalName("MOVE_STATE_SKILL")] Skill = 4,
    [pbr::OriginalName("MOVE_STATE_DIE")] Die = 5,
  }

  public enum MinionState {
    [pbr::OriginalName("MINION_IDLE")] MinionIdle = 0,
    [pbr::OriginalName("MINION_LINE_TRACE")] MinionLineTrace = 1,
    [pbr::OriginalName("MINION_CHASE_TARGET")] MinionChaseTarget = 2,
    [pbr::OriginalName("MINION_ATTACK")] MinionAttack = 3,
    [pbr::OriginalName("MINION_DEAD")] MinionDead = 4,
  }

  public enum SkillType {
    [pbr::OriginalName("SKILL_ID_NONE")] SkillIdNone = 0,
    [pbr::OriginalName("SKILL_ID_ATTACK")] SkillIdAttack = 1,
    [pbr::OriginalName("SKILL_ID_FIRST")] SkillIdFirst = 2,
    [pbr::OriginalName("SKILL_ID_SECOND")] SkillIdSecond = 3,
  }

  public enum CampType {
    [pbr::OriginalName("CAMP_NONE")] CampNone = 0,
    [pbr::OriginalName("CAMP_HUMAN")] CampHuman = 1,
    [pbr::OriginalName("CAMP_CYBORG")] CampCyborg = 2,
    [pbr::OriginalName("CAMP_NEUTURAL")] CampNeutural = 3,
  }

  public enum CellFlags {
    [pbr::OriginalName("CELL_WALKABLE")] CellWalkable = 0,
  }

  public enum CellLinks {
    [pbr::OriginalName("LINK_NORTH")] LinkNorth = 0,
    [pbr::OriginalName("LINK_EAST")] LinkEast = 1,
    [pbr::OriginalName("LINK_SOUTH")] LinkSouth = 2,
    [pbr::OriginalName("LINK_WEST")] LinkWest = 3,
  }

  #endregion

}

#endregion Designer generated code
